version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker/username
    DOCKER_REGISTRY_PASSWORD: /docker/password
    DOCKER_REGISTRY_URL: /docker/url

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r day-14/simple-python-app/requirements.txt

  pre_build:
    commands:
      - echo "Fetching Docker credentials from AWS Systems Manager..."
      - export DOCKER_USERNAME=$(aws ssm get-parameter --name "/docker/username" --with-decryption --query "Parameter.Value" --output text)
      - export DOCKER_PASSWORD=$(aws ssm get-parameter --name "/docker/password" --with-decryption --query "Parameter.Value" --output text)
      - export DOCKER_URL=$(aws ssm get-parameter --name "/docker/url" --with-decryption --query "Parameter.Value" --output text)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"

  build:
    commands:
      - echo "Building Docker image..."
      - cd day-14/simple-python-app/
      - docker build -t "ahmadali616/sample-python:latest" .
      - echo "Pushing Docker image to Docker Hub..."
      - docker push "ahmadali616/sample-python:latest"

  post_build:
    commands:
      - echo "Build and push successful!"

artifacts:
  files:
    - '**/*'
  base-directory: day-14/simple-python-app  
  
